# Site settings
title: Tom Callister
subtitle: 
email: thomas.a.callister@gmail.com
description: 
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Social settings
500px_url: 
facebook_url:
github_url: https://github.com/tcallister
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
googlescholar_url: https://scholar.google.com/citations?user=yFMi2DAAAAAJ&hl=en

# Build settings
markdown: kramdown
